import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';
import '../models/level.dart';

extension LevelLocalizations on Level {
  /// Retourne le titre localisé du niveau selon la langue actuelle.
  /// Si aucune clé de traduction n'est disponible ou si la traduction échoue,
  /// retourne le titre français par défaut.
  String getLocalizedTitle(BuildContext context) {
    if (titleKey == null || titleKey!.isEmpty) {
      return title;
    }

    try {
      final localizations = AppLocalizations.of(context);
      if (localizations == null) {
        return title;
      }

      // Mapping complet de toutes les traductions générées
      return _getTranslation(localizations, titleKey!, title);
    } catch (e) {
      // En cas d'erreur, retourner le titre français
      return title;
    }
  }

  /// Méthode helper pour obtenir une traduction spécifique
  String _getTranslation(AppLocalizations localizations, String key, String fallback) {
    try {
      switch (key) {
        case 'quizTitle_assists_team_period_123':
          return localizations.quizTitle_assists_team_period_123;
        case 'quizTitle_assists_team_period_133':
          return localizations.quizTitle_assists_team_period_133;
        case 'quizTitle_assists_team_period_138':
          return localizations.quizTitle_assists_team_period_138;
        case 'quizTitle_assists_team_period_146':
          return localizations.quizTitle_assists_team_period_146;
        case 'quizTitle_assists_team_period_147':
          return localizations.quizTitle_assists_team_period_147;
        case 'quizTitle_assists_team_period_155':
          return localizations.quizTitle_assists_team_period_155;
        case 'quizTitle_assists_team_period_165':
          return localizations.quizTitle_assists_team_period_165;
        case 'quizTitle_assists_team_period_174':
          return localizations.quizTitle_assists_team_period_174;
        case 'quizTitle_assists_team_period_185':
          return localizations.quizTitle_assists_team_period_185;
        case 'quizTitle_assists_team_period_186':
          return localizations.quizTitle_assists_team_period_186;
        case 'quizTitle_assists_team_period_188':
          return localizations.quizTitle_assists_team_period_188;
        case 'quizTitle_assists_team_period_200':
          return localizations.quizTitle_assists_team_period_200;
        case 'quizTitle_assists_team_period_208':
          return localizations.quizTitle_assists_team_period_208;
        case 'quizTitle_assists_team_period_210':
          return localizations.quizTitle_assists_team_period_210;
        case 'quizTitle_assists_team_period_212':
          return localizations.quizTitle_assists_team_period_212;
        case 'quizTitle_assists_team_period_224':
          return localizations.quizTitle_assists_team_period_224;
        case 'quizTitle_assists_team_period_231':
          return localizations.quizTitle_assists_team_period_231;
        case 'quizTitle_assists_team_period_233':
          return localizations.quizTitle_assists_team_period_233;
        case 'quizTitle_assists_team_period_236':
          return localizations.quizTitle_assists_team_period_236;
        case 'quizTitle_assists_team_period_24':
          return localizations.quizTitle_assists_team_period_24;
        case 'quizTitle_assists_team_period_244':
          return localizations.quizTitle_assists_team_period_244;
        case 'quizTitle_assists_team_period_247':
          return localizations.quizTitle_assists_team_period_247;
        case 'quizTitle_assists_team_period_250':
          return localizations.quizTitle_assists_team_period_250;
        case 'quizTitle_assists_team_period_252':
          return localizations.quizTitle_assists_team_period_252;
        case 'quizTitle_assists_team_period_255':
          return localizations.quizTitle_assists_team_period_255;
        case 'quizTitle_assists_team_period_272':
          return localizations.quizTitle_assists_team_period_272;
        case 'quizTitle_assists_team_period_284':
          return localizations.quizTitle_assists_team_period_284;
        case 'quizTitle_assists_team_period_298':
          return localizations.quizTitle_assists_team_period_298;
        case 'quizTitle_assists_team_period_314':
          return localizations.quizTitle_assists_team_period_314;
        case 'quizTitle_assists_team_period_328':
          return localizations.quizTitle_assists_team_period_328;
        case 'quizTitle_assists_team_period_350':
          return localizations.quizTitle_assists_team_period_350;
        case 'quizTitle_assists_team_period_360':
          return localizations.quizTitle_assists_team_period_360;
        case 'quizTitle_assists_team_period_362':
          return localizations.quizTitle_assists_team_period_362;
        case 'quizTitle_assists_team_period_369':
          return localizations.quizTitle_assists_team_period_369;
        case 'quizTitle_assists_team_period_388':
          return localizations.quizTitle_assists_team_period_388;
        case 'quizTitle_assists_team_period_392':
          return localizations.quizTitle_assists_team_period_392;
        case 'quizTitle_assists_team_period_397':
          return localizations.quizTitle_assists_team_period_397;
        case 'quizTitle_assists_team_period_4':
          return localizations.quizTitle_assists_team_period_4;
        case 'quizTitle_assists_team_period_402':
          return localizations.quizTitle_assists_team_period_402;
        case 'quizTitle_assists_team_period_409':
          return localizations.quizTitle_assists_team_period_409;
        case 'quizTitle_assists_team_period_415':
          return localizations.quizTitle_assists_team_period_415;
        case 'quizTitle_assists_team_period_418':
          return localizations.quizTitle_assists_team_period_418;
        case 'quizTitle_assists_team_period_419':
          return localizations.quizTitle_assists_team_period_419;
        case 'quizTitle_assists_team_period_446':
          return localizations.quizTitle_assists_team_period_446;
        case 'quizTitle_assists_team_period_452':
          return localizations.quizTitle_assists_team_period_452;
        case 'quizTitle_assists_team_period_479':
          return localizations.quizTitle_assists_team_period_479;
        case 'quizTitle_assists_team_period_53':
          return localizations.quizTitle_assists_team_period_53;
        case 'quizTitle_assists_team_period_59':
          return localizations.quizTitle_assists_team_period_59;
        case 'quizTitle_ballon_dor_year_0':
          return localizations.quizTitle_ballon_dor_year_0;
        case 'quizTitle_ballon_dor_year_10':
          return localizations.quizTitle_ballon_dor_year_10;
        case 'quizTitle_ballon_dor_year_101':
          return localizations.quizTitle_ballon_dor_year_101;
        case 'quizTitle_ballon_dor_year_105':
          return localizations.quizTitle_ballon_dor_year_105;
        case 'quizTitle_ballon_dor_year_182':
          return localizations.quizTitle_ballon_dor_year_182;
        case 'quizTitle_ballon_dor_year_19':
          return localizations.quizTitle_ballon_dor_year_19;
        case 'quizTitle_ballon_dor_year_202':
          return localizations.quizTitle_ballon_dor_year_202;
        case 'quizTitle_ballon_dor_year_203':
          return localizations.quizTitle_ballon_dor_year_203;
        case 'quizTitle_ballon_dor_year_214':
          return localizations.quizTitle_ballon_dor_year_214;
        case 'quizTitle_ballon_dor_year_22':
          return localizations.quizTitle_ballon_dor_year_22;
        case 'quizTitle_ballon_dor_year_220':
          return localizations.quizTitle_ballon_dor_year_220;
        case 'quizTitle_ballon_dor_year_222':
          return localizations.quizTitle_ballon_dor_year_222;
        case 'quizTitle_ballon_dor_year_240':
          return localizations.quizTitle_ballon_dor_year_240;
        case 'quizTitle_ballon_dor_year_279':
          return localizations.quizTitle_ballon_dor_year_279;
        case 'quizTitle_ballon_dor_year_292':
          return localizations.quizTitle_ballon_dor_year_292;
        case 'quizTitle_ballon_dor_year_31':
          return localizations.quizTitle_ballon_dor_year_31;
        case 'quizTitle_ballon_dor_year_322':
          return localizations.quizTitle_ballon_dor_year_322;
        case 'quizTitle_ballon_dor_year_324':
          return localizations.quizTitle_ballon_dor_year_324;
        case 'quizTitle_ballon_dor_year_326':
          return localizations.quizTitle_ballon_dor_year_326;
        case 'quizTitle_ballon_dor_year_330':
          return localizations.quizTitle_ballon_dor_year_330;
        case 'quizTitle_ballon_dor_year_338':
          return localizations.quizTitle_ballon_dor_year_338;
        case 'quizTitle_ballon_dor_year_377':
          return localizations.quizTitle_ballon_dor_year_377;
        case 'quizTitle_ballon_dor_year_386':
          return localizations.quizTitle_ballon_dor_year_386;
        case 'quizTitle_ballon_dor_year_399':
          return localizations.quizTitle_ballon_dor_year_399;
        case 'quizTitle_ballon_dor_year_417':
          return localizations.quizTitle_ballon_dor_year_417;
        case 'quizTitle_ballon_dor_year_444':
          return localizations.quizTitle_ballon_dor_year_444;
        case 'quizTitle_ballon_dor_year_453':
          return localizations.quizTitle_ballon_dor_year_453;
        case 'quizTitle_ballon_dor_year_5':
          return localizations.quizTitle_ballon_dor_year_5;
        case 'quizTitle_ballon_dor_year_50':
          return localizations.quizTitle_ballon_dor_year_50;
        case 'quizTitle_ballon_dor_year_51':
          return localizations.quizTitle_ballon_dor_year_51;
        case 'quizTitle_ballon_dor_year_73':
          return localizations.quizTitle_ballon_dor_year_73;
        case 'quizTitle_ballon_dor_year_98':
          return localizations.quizTitle_ballon_dor_year_98;
        case 'quizTitle_expensive_transfers_period_league_107':
          return localizations.quizTitle_expensive_transfers_period_league_107;
        case 'quizTitle_expensive_transfers_period_league_113':
          return localizations.quizTitle_expensive_transfers_period_league_113;
        case 'quizTitle_expensive_transfers_period_league_115':
          return localizations.quizTitle_expensive_transfers_period_league_115;
        case 'quizTitle_expensive_transfers_period_league_116':
          return localizations.quizTitle_expensive_transfers_period_league_116;
        case 'quizTitle_expensive_transfers_period_league_124':
          return localizations.quizTitle_expensive_transfers_period_league_124;
        case 'quizTitle_expensive_transfers_period_league_145':
          return localizations.quizTitle_expensive_transfers_period_league_145;
        case 'quizTitle_expensive_transfers_period_league_150':
          return localizations.quizTitle_expensive_transfers_period_league_150;
        case 'quizTitle_expensive_transfers_period_league_154':
          return localizations.quizTitle_expensive_transfers_period_league_154;
        case 'quizTitle_expensive_transfers_period_league_156':
          return localizations.quizTitle_expensive_transfers_period_league_156;
        case 'quizTitle_expensive_transfers_period_league_157':
          return localizations.quizTitle_expensive_transfers_period_league_157;
        case 'quizTitle_expensive_transfers_period_league_160':
          return localizations.quizTitle_expensive_transfers_period_league_160;
        case 'quizTitle_expensive_transfers_period_league_178':
          return localizations.quizTitle_expensive_transfers_period_league_178;
        case 'quizTitle_expensive_transfers_period_league_183':
          return localizations.quizTitle_expensive_transfers_period_league_183;
        case 'quizTitle_expensive_transfers_period_league_184':
          return localizations.quizTitle_expensive_transfers_period_league_184;
        case 'quizTitle_expensive_transfers_period_league_190':
          return localizations.quizTitle_expensive_transfers_period_league_190;
        case 'quizTitle_expensive_transfers_period_league_192':
          return localizations.quizTitle_expensive_transfers_period_league_192;
        case 'quizTitle_expensive_transfers_period_league_207':
          return localizations.quizTitle_expensive_transfers_period_league_207;
        case 'quizTitle_expensive_transfers_period_league_216':
          return localizations.quizTitle_expensive_transfers_period_league_216;
        case 'quizTitle_expensive_transfers_period_league_218':
          return localizations.quizTitle_expensive_transfers_period_league_218;
        case 'quizTitle_expensive_transfers_period_league_219':
          return localizations.quizTitle_expensive_transfers_period_league_219;
        case 'quizTitle_expensive_transfers_period_league_221':
          return localizations.quizTitle_expensive_transfers_period_league_221;
        case 'quizTitle_expensive_transfers_period_league_228':
          return localizations.quizTitle_expensive_transfers_period_league_228;
        case 'quizTitle_expensive_transfers_period_league_237':
          return localizations.quizTitle_expensive_transfers_period_league_237;
        case 'quizTitle_expensive_transfers_period_league_248':
          return localizations.quizTitle_expensive_transfers_period_league_248;
        case 'quizTitle_expensive_transfers_period_league_251':
          return localizations.quizTitle_expensive_transfers_period_league_251;
        case 'quizTitle_expensive_transfers_period_league_262':
          return localizations.quizTitle_expensive_transfers_period_league_262;
        case 'quizTitle_expensive_transfers_period_league_28':
          return localizations.quizTitle_expensive_transfers_period_league_28;
        case 'quizTitle_expensive_transfers_period_league_290':
          return localizations.quizTitle_expensive_transfers_period_league_290;
        case 'quizTitle_expensive_transfers_period_league_293':
          return localizations.quizTitle_expensive_transfers_period_league_293;
        case 'quizTitle_expensive_transfers_period_league_294':
          return localizations.quizTitle_expensive_transfers_period_league_294;
        case 'quizTitle_expensive_transfers_period_league_296':
          return localizations.quizTitle_expensive_transfers_period_league_296;
        case 'quizTitle_expensive_transfers_period_league_30':
          return localizations.quizTitle_expensive_transfers_period_league_30;
        case 'quizTitle_expensive_transfers_period_league_302':
          return localizations.quizTitle_expensive_transfers_period_league_302;
        case 'quizTitle_expensive_transfers_period_league_303':
          return localizations.quizTitle_expensive_transfers_period_league_303;
        case 'quizTitle_expensive_transfers_period_league_304':
          return localizations.quizTitle_expensive_transfers_period_league_304;
        case 'quizTitle_expensive_transfers_period_league_311':
          return localizations.quizTitle_expensive_transfers_period_league_311;
        case 'quizTitle_expensive_transfers_period_league_312':
          return localizations.quizTitle_expensive_transfers_period_league_312;
        case 'quizTitle_expensive_transfers_period_league_317':
          return localizations.quizTitle_expensive_transfers_period_league_317;
        case 'quizTitle_expensive_transfers_period_league_318':
          return localizations.quizTitle_expensive_transfers_period_league_318;
        case 'quizTitle_expensive_transfers_period_league_319':
          return localizations.quizTitle_expensive_transfers_period_league_319;
        case 'quizTitle_expensive_transfers_period_league_32':
          return localizations.quizTitle_expensive_transfers_period_league_32;
        case 'quizTitle_expensive_transfers_period_league_320':
          return localizations.quizTitle_expensive_transfers_period_league_320;
        case 'quizTitle_expensive_transfers_period_league_325':
          return localizations.quizTitle_expensive_transfers_period_league_325;
        case 'quizTitle_expensive_transfers_period_league_340':
          return localizations.quizTitle_expensive_transfers_period_league_340;
        case 'quizTitle_expensive_transfers_period_league_341':
          return localizations.quizTitle_expensive_transfers_period_league_341;
        case 'quizTitle_expensive_transfers_period_league_353':
          return localizations.quizTitle_expensive_transfers_period_league_353;
        case 'quizTitle_expensive_transfers_period_league_354':
          return localizations.quizTitle_expensive_transfers_period_league_354;
        case 'quizTitle_expensive_transfers_period_league_356':
          return localizations.quizTitle_expensive_transfers_period_league_356;
        case 'quizTitle_expensive_transfers_period_league_357':
          return localizations.quizTitle_expensive_transfers_period_league_357;
        case 'quizTitle_expensive_transfers_period_league_363':
          return localizations.quizTitle_expensive_transfers_period_league_363;
        case 'quizTitle_expensive_transfers_period_league_366':
          return localizations.quizTitle_expensive_transfers_period_league_366;
        case 'quizTitle_expensive_transfers_period_league_37':
          return localizations.quizTitle_expensive_transfers_period_league_37;
        case 'quizTitle_expensive_transfers_period_league_403':
          return localizations.quizTitle_expensive_transfers_period_league_403;
        case 'quizTitle_expensive_transfers_period_league_405':
          return localizations.quizTitle_expensive_transfers_period_league_405;
        case 'quizTitle_expensive_transfers_period_league_406':
          return localizations.quizTitle_expensive_transfers_period_league_406;
        case 'quizTitle_expensive_transfers_period_league_408':
          return localizations.quizTitle_expensive_transfers_period_league_408;
        case 'quizTitle_expensive_transfers_period_league_41':
          return localizations.quizTitle_expensive_transfers_period_league_41;
        case 'quizTitle_expensive_transfers_period_league_410':
          return localizations.quizTitle_expensive_transfers_period_league_410;
        case 'quizTitle_expensive_transfers_period_league_412':
          return localizations.quizTitle_expensive_transfers_period_league_412;
        case 'quizTitle_expensive_transfers_period_league_416':
          return localizations.quizTitle_expensive_transfers_period_league_416;
        case 'quizTitle_expensive_transfers_period_league_434':
          return localizations.quizTitle_expensive_transfers_period_league_434;
        case 'quizTitle_expensive_transfers_period_league_436':
          return localizations.quizTitle_expensive_transfers_period_league_436;
        case 'quizTitle_expensive_transfers_period_league_437':
          return localizations.quizTitle_expensive_transfers_period_league_437;
        case 'quizTitle_expensive_transfers_period_league_438':
          return localizations.quizTitle_expensive_transfers_period_league_438;
        case 'quizTitle_expensive_transfers_period_league_443':
          return localizations.quizTitle_expensive_transfers_period_league_443;
        case 'quizTitle_expensive_transfers_period_league_45':
          return localizations.quizTitle_expensive_transfers_period_league_45;
        case 'quizTitle_expensive_transfers_period_league_450':
          return localizations.quizTitle_expensive_transfers_period_league_450;
        case 'quizTitle_expensive_transfers_period_league_451':
          return localizations.quizTitle_expensive_transfers_period_league_451;
        case 'quizTitle_expensive_transfers_period_league_46':
          return localizations.quizTitle_expensive_transfers_period_league_46;
        case 'quizTitle_expensive_transfers_period_league_463':
          return localizations.quizTitle_expensive_transfers_period_league_463;
        case 'quizTitle_expensive_transfers_period_league_464':
          return localizations.quizTitle_expensive_transfers_period_league_464;
        case 'quizTitle_expensive_transfers_period_league_465':
          return localizations.quizTitle_expensive_transfers_period_league_465;
        case 'quizTitle_expensive_transfers_period_league_469':
          return localizations.quizTitle_expensive_transfers_period_league_469;
        case 'quizTitle_expensive_transfers_period_league_470':
          return localizations.quizTitle_expensive_transfers_period_league_470;
        case 'quizTitle_expensive_transfers_period_league_49':
          return localizations.quizTitle_expensive_transfers_period_league_49;
        case 'quizTitle_expensive_transfers_period_league_52':
          return localizations.quizTitle_expensive_transfers_period_league_52;
        case 'quizTitle_expensive_transfers_period_league_56':
          return localizations.quizTitle_expensive_transfers_period_league_56;
        case 'quizTitle_expensive_transfers_period_league_57':
          return localizations.quizTitle_expensive_transfers_period_league_57;
        case 'quizTitle_expensive_transfers_period_league_62':
          return localizations.quizTitle_expensive_transfers_period_league_62;
        case 'quizTitle_expensive_transfers_period_league_64':
          return localizations.quizTitle_expensive_transfers_period_league_64;
        case 'quizTitle_expensive_transfers_period_league_68':
          return localizations.quizTitle_expensive_transfers_period_league_68;
        case 'quizTitle_expensive_transfers_period_league_72':
          return localizations.quizTitle_expensive_transfers_period_league_72;
        case 'quizTitle_expensive_transfers_period_league_77':
          return localizations.quizTitle_expensive_transfers_period_league_77;
        case 'quizTitle_expensive_transfers_period_league_78':
          return localizations.quizTitle_expensive_transfers_period_league_78;
        case 'quizTitle_expensive_transfers_period_league_8':
          return localizations.quizTitle_expensive_transfers_period_league_8;
        case 'quizTitle_expensive_transfers_period_league_84':
          return localizations.quizTitle_expensive_transfers_period_league_84;
        case 'quizTitle_expensive_transfers_period_league_86':
          return localizations.quizTitle_expensive_transfers_period_league_86;
        case 'quizTitle_expensive_transfers_period_league_94':
          return localizations.quizTitle_expensive_transfers_period_league_94;
        case 'quizTitle_most_minutes_team_year_100':
          return localizations.quizTitle_most_minutes_team_year_100;
        case 'quizTitle_most_minutes_team_year_111':
          return localizations.quizTitle_most_minutes_team_year_111;
        case 'quizTitle_most_minutes_team_year_119':
          return localizations.quizTitle_most_minutes_team_year_119;
        case 'quizTitle_most_minutes_team_year_121':
          return localizations.quizTitle_most_minutes_team_year_121;
        case 'quizTitle_most_minutes_team_year_131':
          return localizations.quizTitle_most_minutes_team_year_131;
        case 'quizTitle_most_minutes_team_year_137':
          return localizations.quizTitle_most_minutes_team_year_137;
        case 'quizTitle_most_minutes_team_year_139':
          return localizations.quizTitle_most_minutes_team_year_139;
        case 'quizTitle_most_minutes_team_year_14':
          return localizations.quizTitle_most_minutes_team_year_14;
        case 'quizTitle_most_minutes_team_year_140':
          return localizations.quizTitle_most_minutes_team_year_140;
        case 'quizTitle_most_minutes_team_year_141':
          return localizations.quizTitle_most_minutes_team_year_141;
        case 'quizTitle_most_minutes_team_year_143':
          return localizations.quizTitle_most_minutes_team_year_143;
        case 'quizTitle_most_minutes_team_year_148':
          return localizations.quizTitle_most_minutes_team_year_148;
        case 'quizTitle_most_minutes_team_year_152':
          return localizations.quizTitle_most_minutes_team_year_152;
        case 'quizTitle_most_minutes_team_year_158':
          return localizations.quizTitle_most_minutes_team_year_158;
        case 'quizTitle_most_minutes_team_year_159':
          return localizations.quizTitle_most_minutes_team_year_159;
        case 'quizTitle_most_minutes_team_year_162':
          return localizations.quizTitle_most_minutes_team_year_162;
        case 'quizTitle_most_minutes_team_year_164':
          return localizations.quizTitle_most_minutes_team_year_164;
        case 'quizTitle_most_minutes_team_year_17':
          return localizations.quizTitle_most_minutes_team_year_17;
        case 'quizTitle_most_minutes_team_year_180':
          return localizations.quizTitle_most_minutes_team_year_180;
        case 'quizTitle_most_minutes_team_year_193':
          return localizations.quizTitle_most_minutes_team_year_193;
        case 'quizTitle_most_minutes_team_year_197':
          return localizations.quizTitle_most_minutes_team_year_197;
        case 'quizTitle_most_minutes_team_year_206':
          return localizations.quizTitle_most_minutes_team_year_206;
        case 'quizTitle_most_minutes_team_year_223':
          return localizations.quizTitle_most_minutes_team_year_223;
        case 'quizTitle_most_minutes_team_year_225':
          return localizations.quizTitle_most_minutes_team_year_225;
        case 'quizTitle_most_minutes_team_year_229':
          return localizations.quizTitle_most_minutes_team_year_229;
        case 'quizTitle_most_minutes_team_year_234':
          return localizations.quizTitle_most_minutes_team_year_234;
        case 'quizTitle_most_minutes_team_year_254':
          return localizations.quizTitle_most_minutes_team_year_254;
        case 'quizTitle_most_minutes_team_year_260':
          return localizations.quizTitle_most_minutes_team_year_260;
        case 'quizTitle_most_minutes_team_year_266':
          return localizations.quizTitle_most_minutes_team_year_266;
        case 'quizTitle_most_minutes_team_year_269':
          return localizations.quizTitle_most_minutes_team_year_269;
        case 'quizTitle_most_minutes_team_year_276':
          return localizations.quizTitle_most_minutes_team_year_276;
        case 'quizTitle_most_minutes_team_year_280':
          return localizations.quizTitle_most_minutes_team_year_280;
        case 'quizTitle_most_minutes_team_year_283':
          return localizations.quizTitle_most_minutes_team_year_283;
        case 'quizTitle_most_minutes_team_year_288':
          return localizations.quizTitle_most_minutes_team_year_288;
        case 'quizTitle_most_minutes_team_year_29':
          return localizations.quizTitle_most_minutes_team_year_29;
        case 'quizTitle_most_minutes_team_year_300':
          return localizations.quizTitle_most_minutes_team_year_300;
        case 'quizTitle_most_minutes_team_year_315':
          return localizations.quizTitle_most_minutes_team_year_315;
        case 'quizTitle_most_minutes_team_year_327':
          return localizations.quizTitle_most_minutes_team_year_327;
        case 'quizTitle_most_minutes_team_year_33':
          return localizations.quizTitle_most_minutes_team_year_33;
        case 'quizTitle_most_minutes_team_year_334':
          return localizations.quizTitle_most_minutes_team_year_334;
        case 'quizTitle_most_minutes_team_year_335':
          return localizations.quizTitle_most_minutes_team_year_335;
        case 'quizTitle_most_minutes_team_year_336':
          return localizations.quizTitle_most_minutes_team_year_336;
        case 'quizTitle_most_minutes_team_year_343':
          return localizations.quizTitle_most_minutes_team_year_343;
        case 'quizTitle_most_minutes_team_year_344':
          return localizations.quizTitle_most_minutes_team_year_344;
        case 'quizTitle_most_minutes_team_year_346':
          return localizations.quizTitle_most_minutes_team_year_346;
        case 'quizTitle_most_minutes_team_year_352':
          return localizations.quizTitle_most_minutes_team_year_352;
        case 'quizTitle_most_minutes_team_year_358':
          return localizations.quizTitle_most_minutes_team_year_358;
        case 'quizTitle_most_minutes_team_year_361':
          return localizations.quizTitle_most_minutes_team_year_361;
        case 'quizTitle_most_minutes_team_year_367':
          return localizations.quizTitle_most_minutes_team_year_367;
        case 'quizTitle_most_minutes_team_year_372':
          return localizations.quizTitle_most_minutes_team_year_372;
        case 'quizTitle_most_minutes_team_year_38':
          return localizations.quizTitle_most_minutes_team_year_38;
        case 'quizTitle_most_minutes_team_year_387':
          return localizations.quizTitle_most_minutes_team_year_387;
        case 'quizTitle_most_minutes_team_year_398':
          return localizations.quizTitle_most_minutes_team_year_398;
        case 'quizTitle_most_minutes_team_year_407':
          return localizations.quizTitle_most_minutes_team_year_407;
        case 'quizTitle_most_minutes_team_year_413':
          return localizations.quizTitle_most_minutes_team_year_413;
        case 'quizTitle_most_minutes_team_year_414':
          return localizations.quizTitle_most_minutes_team_year_414;
        case 'quizTitle_most_minutes_team_year_421':
          return localizations.quizTitle_most_minutes_team_year_421;
        case 'quizTitle_most_minutes_team_year_424':
          return localizations.quizTitle_most_minutes_team_year_424;
        case 'quizTitle_most_minutes_team_year_427':
          return localizations.quizTitle_most_minutes_team_year_427;
        case 'quizTitle_most_minutes_team_year_429':
          return localizations.quizTitle_most_minutes_team_year_429;
        case 'quizTitle_most_minutes_team_year_435':
          return localizations.quizTitle_most_minutes_team_year_435;
        case 'quizTitle_most_minutes_team_year_448':
          return localizations.quizTitle_most_minutes_team_year_448;
        case 'quizTitle_most_minutes_team_year_454':
          return localizations.quizTitle_most_minutes_team_year_454;
        case 'quizTitle_most_minutes_team_year_458':
          return localizations.quizTitle_most_minutes_team_year_458;
        case 'quizTitle_most_minutes_team_year_460':
          return localizations.quizTitle_most_minutes_team_year_460;
        case 'quizTitle_most_minutes_team_year_461':
          return localizations.quizTitle_most_minutes_team_year_461;
        case 'quizTitle_most_minutes_team_year_462':
          return localizations.quizTitle_most_minutes_team_year_462;
        case 'quizTitle_most_minutes_team_year_472':
          return localizations.quizTitle_most_minutes_team_year_472;
        case 'quizTitle_most_minutes_team_year_473':
          return localizations.quizTitle_most_minutes_team_year_473;
        case 'quizTitle_most_minutes_team_year_48':
          return localizations.quizTitle_most_minutes_team_year_48;
        case 'quizTitle_most_minutes_team_year_55':
          return localizations.quizTitle_most_minutes_team_year_55;
        case 'quizTitle_most_minutes_team_year_61':
          return localizations.quizTitle_most_minutes_team_year_61;
        case 'quizTitle_most_minutes_team_year_66':
          return localizations.quizTitle_most_minutes_team_year_66;
        case 'quizTitle_most_minutes_team_year_70':
          return localizations.quizTitle_most_minutes_team_year_70;
        case 'quizTitle_most_minutes_team_year_74':
          return localizations.quizTitle_most_minutes_team_year_74;
        case 'quizTitle_most_minutes_team_year_82':
          return localizations.quizTitle_most_minutes_team_year_82;
        case 'quizTitle_most_minutes_team_year_87':
          return localizations.quizTitle_most_minutes_team_year_87;
        case 'quizTitle_most_minutes_team_year_89':
          return localizations.quizTitle_most_minutes_team_year_89;
        case 'quizTitle_most_minutes_team_year_9':
          return localizations.quizTitle_most_minutes_team_year_9;
        case 'quizTitle_most_minutes_team_year_95':
          return localizations.quizTitle_most_minutes_team_year_95;
        case 'quizTitle_scorers_team_period_110':
          return localizations.quizTitle_scorers_team_period_110;
        case 'quizTitle_scorers_team_period_126':
          return localizations.quizTitle_scorers_team_period_126;
        case 'quizTitle_scorers_team_period_128':
          return localizations.quizTitle_scorers_team_period_128;
        case 'quizTitle_scorers_team_period_130':
          return localizations.quizTitle_scorers_team_period_130;
        case 'quizTitle_scorers_team_period_136':
          return localizations.quizTitle_scorers_team_period_136;
        case 'quizTitle_scorers_team_period_151':
          return localizations.quizTitle_scorers_team_period_151;
        case 'quizTitle_scorers_team_period_161':
          return localizations.quizTitle_scorers_team_period_161;
        case 'quizTitle_scorers_team_period_170':
          return localizations.quizTitle_scorers_team_period_170;
        case 'quizTitle_scorers_team_period_172':
          return localizations.quizTitle_scorers_team_period_172;
        case 'quizTitle_scorers_team_period_196':
          return localizations.quizTitle_scorers_team_period_196;
        case 'quizTitle_scorers_team_period_204':
          return localizations.quizTitle_scorers_team_period_204;
        case 'quizTitle_scorers_team_period_211':
          return localizations.quizTitle_scorers_team_period_211;
        case 'quizTitle_scorers_team_period_217':
          return localizations.quizTitle_scorers_team_period_217;
        case 'quizTitle_scorers_team_period_226':
          return localizations.quizTitle_scorers_team_period_226;
        case 'quizTitle_scorers_team_period_243':
          return localizations.quizTitle_scorers_team_period_243;
        case 'quizTitle_scorers_team_period_257':
          return localizations.quizTitle_scorers_team_period_257;
        case 'quizTitle_scorers_team_period_263':
          return localizations.quizTitle_scorers_team_period_263;
        case 'quizTitle_scorers_team_period_264':
          return localizations.quizTitle_scorers_team_period_264;
        case 'quizTitle_scorers_team_period_281':
          return localizations.quizTitle_scorers_team_period_281;
        case 'quizTitle_scorers_team_period_285':
          return localizations.quizTitle_scorers_team_period_285;
        case 'quizTitle_scorers_team_period_287':
          return localizations.quizTitle_scorers_team_period_287;
        case 'quizTitle_scorers_team_period_299':
          return localizations.quizTitle_scorers_team_period_299;
        case 'quizTitle_scorers_team_period_306':
          return localizations.quizTitle_scorers_team_period_306;
        case 'quizTitle_scorers_team_period_307':
          return localizations.quizTitle_scorers_team_period_307;
        case 'quizTitle_scorers_team_period_331':
          return localizations.quizTitle_scorers_team_period_331;
        case 'quizTitle_scorers_team_period_339':
          return localizations.quizTitle_scorers_team_period_339;
        case 'quizTitle_scorers_team_period_345':
          return localizations.quizTitle_scorers_team_period_345;
        case 'quizTitle_scorers_team_period_348':
          return localizations.quizTitle_scorers_team_period_348;
        case 'quizTitle_scorers_team_period_349':
          return localizations.quizTitle_scorers_team_period_349;
        case 'quizTitle_scorers_team_period_373':
          return localizations.quizTitle_scorers_team_period_373;
        case 'quizTitle_scorers_team_period_374':
          return localizations.quizTitle_scorers_team_period_374;
        case 'quizTitle_scorers_team_period_380':
          return localizations.quizTitle_scorers_team_period_380;
        case 'quizTitle_scorers_team_period_381':
          return localizations.quizTitle_scorers_team_period_381;
        case 'quizTitle_scorers_team_period_383':
          return localizations.quizTitle_scorers_team_period_383;
        case 'quizTitle_scorers_team_period_384':
          return localizations.quizTitle_scorers_team_period_384;
        case 'quizTitle_scorers_team_period_423':
          return localizations.quizTitle_scorers_team_period_423;
        case 'quizTitle_scorers_team_period_428':
          return localizations.quizTitle_scorers_team_period_428;
        case 'quizTitle_scorers_team_period_43':
          return localizations.quizTitle_scorers_team_period_43;
        case 'quizTitle_scorers_team_period_455':
          return localizations.quizTitle_scorers_team_period_455;
        case 'quizTitle_scorers_team_period_75':
          return localizations.quizTitle_scorers_team_period_75;
        case 'quizTitle_scorers_team_period_90':
          return localizations.quizTitle_scorers_team_period_90;
        case 'quizTitle_scorers_team_year_1':
          return localizations.quizTitle_scorers_team_year_1;
        case 'quizTitle_scorers_team_year_112':
          return localizations.quizTitle_scorers_team_year_112;
        case 'quizTitle_scorers_team_year_118':
          return localizations.quizTitle_scorers_team_year_118;
        case 'quizTitle_scorers_team_year_125':
          return localizations.quizTitle_scorers_team_year_125;
        case 'quizTitle_scorers_team_year_134':
          return localizations.quizTitle_scorers_team_year_134;
        case 'quizTitle_scorers_team_year_15':
          return localizations.quizTitle_scorers_team_year_15;
        case 'quizTitle_scorers_team_year_167':
          return localizations.quizTitle_scorers_team_year_167;
        case 'quizTitle_scorers_team_year_169':
          return localizations.quizTitle_scorers_team_year_169;
        case 'quizTitle_scorers_team_year_175':
          return localizations.quizTitle_scorers_team_year_175;
        case 'quizTitle_scorers_team_year_181':
          return localizations.quizTitle_scorers_team_year_181;
        case 'quizTitle_scorers_team_year_191':
          return localizations.quizTitle_scorers_team_year_191;
        case 'quizTitle_scorers_team_year_20':
          return localizations.quizTitle_scorers_team_year_20;
        case 'quizTitle_scorers_team_year_215':
          return localizations.quizTitle_scorers_team_year_215;
        case 'quizTitle_scorers_team_year_274':
          return localizations.quizTitle_scorers_team_year_274;
        case 'quizTitle_scorers_team_year_289':
          return localizations.quizTitle_scorers_team_year_289;
        case 'quizTitle_scorers_team_year_308':
          return localizations.quizTitle_scorers_team_year_308;
        case 'quizTitle_scorers_team_year_404':
          return localizations.quizTitle_scorers_team_year_404;
        case 'quizTitle_scorers_team_year_44':
          return localizations.quizTitle_scorers_team_year_44;
        case 'quizTitle_scorers_team_year_445':
          return localizations.quizTitle_scorers_team_year_445;
        case 'quizTitle_scorers_team_year_447':
          return localizations.quizTitle_scorers_team_year_447;
        case 'quizTitle_scorers_team_year_6':
          return localizations.quizTitle_scorers_team_year_6;
        case 'quizTitle_scorers_team_year_93':
          return localizations.quizTitle_scorers_team_year_93;
        case 'quizTitle_scorers_team_year_97':
          return localizations.quizTitle_scorers_team_year_97;
        case 'quizTitle_top_10_des_buteurs_de_la_can_2023_102':
          return localizations.quizTitle_top_10_des_buteurs_de_la_can_2023_102;
        case 'quizTitle_top_10_des_buteurs_de_la_can_2023_316':
          return localizations.quizTitle_top_10_des_buteurs_de_la_can_2023_316;
        case 'quizTitle_top_10_des_buteurs_de_la_can_2023_456':
          return localizations.quizTitle_top_10_des_buteurs_de_la_can_2023_456;
        case 'quizTitle_top_10_des_buteurs_de_la_can_2023_477':
          return localizations.quizTitle_top_10_des_buteurs_de_la_can_2023_477;
        case 'quizTitle_top_10_des_buteurs_de_la_copa_america_2024_177':
          return localizations.quizTitle_top_10_des_buteurs_de_la_copa_america_2024_177;
        case 'quizTitle_top_10_des_buteurs_de_la_copa_america_2024_277':
          return localizations.quizTitle_top_10_des_buteurs_de_la_copa_america_2024_277;
        case 'quizTitle_top_10_des_buteurs_de_la_copa_america_2024_295':
          return localizations.quizTitle_top_10_des_buteurs_de_la_copa_america_2024_295;
        case 'quizTitle_top_10_des_buteurs_de_la_copa_america_2024_91':
          return localizations.quizTitle_top_10_des_buteurs_de_la_copa_america_2024_91;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_114':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_114;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_173':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_173;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_249':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_249;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_393':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2018_393;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_104':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_104;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_27':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_27;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_39':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_39;
        case 'quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_396':
          return localizations.quizTitle_top_10_des_buteurs_de_la_coupe_du_monde_2022_396;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2021_168':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2021_168;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2021_227':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2021_227;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2021_342':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2021_342;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2021_457':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2021_457;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2024_149':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2024_149;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2024_189':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2024_189;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2024_35':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2024_35;
        case 'quizTitle_top_10_des_buteurs_de_la_euro_2024_92':
          return localizations.quizTitle_top_10_des_buteurs_de_la_euro_2024_92;
        case 'quizTitle_top_10_des_buteurs_france_dans_les_grands_clubs_eu':
          return localizations.quizTitle_top_10_des_buteurs_france_dans_les_grands_clubs_eu;
        case 'quizTitle_top_10_des_buteurs_portugal_dans_les_grands_clubs':
          return localizations.quizTitle_top_10_des_buteurs_portugal_dans_les_grands_clubs;
        case 'quizTitle_top_10_des_joueurs_avec_le_meilleur_ratio_butsminu':
          return localizations.quizTitle_top_10_des_joueurs_avec_le_meilleur_ratio_butsminu;
        case 'quizTitle_top_10_des_joueurs_france_les_plus_prolifiques_but':
          return localizations.quizTitle_top_10_des_joueurs_france_les_plus_prolifiques_but;
        case 'quizTitle_top_10_des_joueurs_portugal_les_plus_prolifiques_b':
          return localizations.quizTitle_top_10_des_joueurs_portugal_les_plus_prolifiques_b;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_127':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_127;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_209':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_209;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_286':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_286;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_471':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2023_471;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_120':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_120;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_245':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_245;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_378':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_378;
        case 'quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_449':
          return localizations.quizTitle_top_10_des_passeurs_de_bundesliga_en_2024_449;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2022_106':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2022_106;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2022_179':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2022_179;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2022_389':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2022_389;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2022_466':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2022_466;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2023_278':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2023_278;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2023_333':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2023_333;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2023_426':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2023_426;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2023_47':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2023_47;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2024_23':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2024_23;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2024_310':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2024_310;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2024_467':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2024_467;
        case 'quizTitle_top_10_des_passeurs_de_liga_en_2024_478':
          return localizations.quizTitle_top_10_des_passeurs_de_liga_en_2024_478;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_171':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_171;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_201':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_201;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_351':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_351;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_83':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2023_83;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_166':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_166;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_213':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_213;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_379':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_379;
        case 'quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_431':
          return localizations.quizTitle_top_10_des_passeurs_de_ligue_1_en_2024_431;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2022_117':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2022_117;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2022_268':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2022_268;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2022_394':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2022_394;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2022_63':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2022_63;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2023_270':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2023_270;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2023_395':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2023_395;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2023_40':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2023_40;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2023_422':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2023_422;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2024_18':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2024_18;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2024_246':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2024_246;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2024_365':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2024_365;
        case 'quizTitle_top_10_des_passeurs_de_premier_league_en_2024_400':
          return localizations.quizTitle_top_10_des_passeurs_de_premier_league_en_2024_400;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2023_153':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2023_153;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2023_198':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2023_198;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2023_420':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2023_420;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2023_440':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2023_440;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2024_144':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2024_144;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2024_256':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2024_256;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2024_359':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2024_359;
        case 'quizTitle_top_10_des_passeurs_de_serie_a_en_2024_476':
          return localizations.quizTitle_top_10_des_passeurs_de_serie_a_en_2024_476;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_bun':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_bun;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_lig':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_lig;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_pre':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_pre;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_ser':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2022_ser;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_bun':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_bun;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_lig':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_lig;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_pre':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_pre;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_ser':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2023_ser;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_bun':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_bun;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_lig':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_lig;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_pre':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_pre;
        case 'quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_ser':
          return localizations.quizTitle_top_10_des_transferts_les_plus_couteux_en_2024_ser;
        default:
          return fallback;
      }
    } catch (e) {
      return fallback;
    }
  }
}